config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  resources :apidocs, only: [:index]
  get '/api' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')

  devise_for :users
  root 'products#index'

  resources :products, only: %i[index show]

  resources :order_lines, only: %i[new create edit update destroy]

  resources :orders, only: %i[show destroy]

  namespace :admin do
    resources :products, only: %i[destroy] do
      post "add_tag", on: :member
    end
    resources :change_logs, only: %i[index]
    resources :product_forms, only: %i[new create edit update]
    resources :comments, only: %i[destroy]
    patch 'comments/approve' => 'comments#approve'
    resources :transactions, only: %i[index]
  end

  namespace :customer do
    resources :orders, only: %i[index show update destroy]
    resources :likes, only: %i[create destroy]
    resources :order_lines, only: %i[destroy]
    resources :order_line_forms, only: %i[new create edit update]
    resources :comment_products, only: %i[create]
    resources :comment_orders, only: %i[create]
    get 'empty_cart' => 'shopping_cart#empty_cart'
    get 'checkout' => 'shopping_cart#checkout'
    resources :transactions, only: %i[index]
  end

  get 'shopping_cart', to: 'shopping_cart#index'
  get 'empty_cart' => 'shopping_cart#empty_cart'
  get 'checkout' => 'shopping_cart#checkout'

  resources :order_line_forms, only: %i[new create edit update]

  # Api routes
  namespace :api do
    namespace :v1 do
      post '/sign_in' => 'sessions#sign_in'
      resources :products, only: %i[index show]
      # namespace :customer do
        resources :likes, only: %i[create destroy]
        resources :order_lines, only: %i[create]
        resources :orders, only: %i[index]
        resources :comment_users, only: %i[create]
        get 'checkout' => 'orders#checkout'
        resources :transactions, only: %i[index]
      # end
      namespace :admin do
        resources :products, only: %i[index show create update destroy] do 
          patch 'discard', on: :member
          patch 'restore', on: :member
        end
        resources :comments, only: %i[destroy] do
          patch 'approve', on: :member
        end 
        resources :users, only: %i[create] do 
          patch 'discard', on: :member
          patch 'restore', on: :member
        end
        resources :transactions, only: %i[index]
      end
      post 'registration' => 'registration#create'
    end
  end

  get 'forgot_password' => 'password#forgot_password'
  post 'reset_password' => 'password#reset_password'

  post 'checkout_pay' => 'checkout_pay#create'
  resources :webhooks, only: %i[create]
  post 'webhooks/checkout_session_completed' => 'webhooks#checkout_session_completed'
  post 'webhooks/payment_failed' => 'webhooks#payment_failed'
end

app/models/order.rb
# frozen_string_literal: true

# Class to manage Product Model
class Order < ApplicationRecord
  # Associations
  belongs_to :user, optional: true
  has_many :order_lines, dependent: :destroy
  has_many :products, through: :order_lines
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :rates, as: :rateable, dependent: :destroy

  # Enum
  enum :status, %i[pending completed refused]

  # Scopes
  scope :get_orders_beetween_dates_for_a_customer, lambda { |first_date, last_date, customer_id|
                                                     where('created_at BETWEEN ? AND ?', first_date, last_date)
                                                       .where('customer_id = ?', customer_id)
                                                   }

  def add_lines_from_cart(virtual_order)
    virtual_order.each do |detail|
      order_line = OrderLine.create(
        product_id: detail['product']['id'],
        quantity: detail['order_line']['quantity'],
        price: detail['order_line']['price']
      )
      order_lines.push(order_line)
    end
  end

  def calculate_total
    order_lines.reduce(0) { |acc, order_line| acc + order_line.total }
  end
end

app/controllers/api/v1/orders_controller.rb
# frozen_string_literal: true

module Api
  module V1
    # Class to manage orders since api
    class OrdersController < ApiController
      before_action :authorize_request, only: %i[index checkout]
      before_action :set_order, only: %i[checkout]

      # Method to get index of completed orders of a customer user
      # - GET api/v1/orders
      def index
        authorize Order
        @orders = Customer::OrderLister.call(@current_user, 'completed')
        render json: json_api_format(OrderRepresenter.for_collection.new(@orders), 'orders'), status: :ok
      end

      # Method to checkout if there is enough stock for all the products of a shopping cart
      # - GET /api/v1/customer/checkout
      def checkout
        authorize @order
        # @order = Customer::CheckoutHandlerApi.call(params[:order_id])
        session = Customer::StripeCheckoutApiService.call(@current_user, @order, root_url, root_url)
        render json: session, status: :ok
      end

      private

      def set_order
        @order = Order.find(params[:order_id])
      end
    end
  end
end

app/controllers/customer/comment_orders_controller.rb
# frozen_string_literal: true

module Customer
  # Class to manage interactions between logged in customer users and order comments
  class CommentOrdersController < ApplicationController
    before_action :set_order

    # Method to add a new comment
    # - POST /customer/comment_product_forms
    def create
      Customer::Comments::CommentOrderCreator.call(current_user, comment_order_form_params)
      flash[:notice] = 'Comment was successfully added'
    rescue StandardError => e
      flash[:error] = e
    ensure
      redirect_to [:customer, @order]
    end

    private

    # Method to set strong paramas for order line form
    def comment_order_form_params
      params.require(:forms_comment_order_form).permit(:description, :rate_value, :order_id)
    end

    def set_order
      @order = Order.find(comment_order_form_params[:order_id])
    end
  end
end

app/controllers/customer/comment_products_controller.rb
# frozen_string_literal: true

module Customer
  # Class to manage interactions between logged in customer users and comments
  class CommentProductsController < ApplicationController
    before_action :set_product

    # Method to add a new comment
    # - POST /customer/comment_products
    def create
      ctx = run Operations::Customer::Comments::Create,
                params: { comment: params[:comment], current_user: } do
        return redirect_to @product, notice: 'Product was successfully created'
      end
      flash[:error] = ctx['contract.default'].errors.messages
      # Customer::Comments::CommentProductCreator.call(current_user, comment_product_form_params)
      # flash[:notice] = 'Comment was successfully added'
      # rescue StandardError => e
      #   flash[:error] = e
      #  ensure
      redirect_to @product
    end

    private

    # Method to set strong params for comment product
    # def comment_product_form_params
    #   params.require(:forms_comment_product_form).permit(:description, :rate_value, :product_id)
    # end

    def set_product
      # @product = Product.find(comment_product_form_params[:product_id])
      @product = Product.find(params[:comment][:product_id])
    end
  end
end

app/controllers/customer/likes_controller.rb
# frozen_string_literal: true

module Customer
  # Class to manage Likes of a product
  class LikesController < ApplicationController
    before_action :authorize_action

    # Method to like a product
    # - POST /customer/likes
    def create
      run Operations::Customer::Likes::Create, params:, current_user: do
        redirect_to products_path, notice: 'Product liked successfully'
      end
      # Customer::Likes::LikeHandler.call(current_user, params[:product_id])
    end

    # Method to dislike a product
    # - DELETE /customer/likes/:id
    def destroy
      run Operations::Customer::Likes::Delete
      # Customer::Likes::DislikeHandler.call(params[:id])
      redirect_to products_path, notice: 'Product disliked successfully'
    end

    private

    def authorize_action
      authorize Like
    end
  end
end

app/controllers/customer/order_line_forms_controller.rb
# frozen_string_literal: true

module Customer
  # Class to manage interactions between logged in customer users and order lines of a shopping cart
  class OrderLineFormsController < ApplicationController
    skip_before_action :load_pending_order
    before_action :set_order, only: %i[create update]
    before_action :authorize_action
    after_action :reset_session, only: %i[create update]
    after_action :set_values, only: %i[new edit]

    # Method to get the form to add a new product (order line) to shopping cart
    # - GET /customer/order_line_forms/new
    def new
      run Operations::Customer::OrderLines::Create::Present do |ctx|
        @order_line_form = ctx['contract.default']
        @product = ctx[:product]
      end
    end

    # Method to add a new product (order line) to shopping cart
    # - POST /customer/order_line_forms
    def create
      ctx = run Operations::Customer::OrderLines::Create, params:, current_user:, order: @order do
        return redirect_to shopping_cart_path, notice: 'Product was successfully added'
      end
      @product = ctx[:product]
      @order_line_form = ctx['contract.default']
      render :new
    end

    # Method to get the form to update an order line of the shopping cart
    # - GET /customer/order_line_forms/:id/edit
    def edit
      # @order_line_form = Customer::OrderLines::EditFormGetter.call({ id: params[:id], product_id: params[:product_id] },
      #                                                              current_user)

      run Operations::Customer::OrderLines::Update::Present, params: do |ctx|
        @order_line_form = ctx['contract.default']
        @product = ctx[:product]
      end

      # rescue StandardError => e
      #   flash[:alert] = e
      #   session[:order_id] = nil
      # redirect_to products_path
    end

    # Method to update an order line of the shopping cart
    # - PATCH /customer/order_line_forms/:id
    def update
      # @order_line = Customer::OrderLines::OrderLineUpdater.call(order_line_form_params, @order)
      # redirect_to shopping_cart_path, notice: 'Quantity was successfully updated'
      ctx = run Operations::Customer::OrderLines::Update, params:, order: @order do
        return redirect_to shopping_cart_path, notice: 'Quantity was successfully updated'
      end
      @product = ctx[:product]
      @order_line_form = ctx['contract.default']
      render :edit
    # rescue StandardError => e
    #   flash[:error] = e
    #   redirect_to edit_customer_order_line_form_path(product_id: session[:product_id])
    end

    private

    # Method to set strong paramas for order line form
    def order_line_form_params
      params.require(:forms_order_line_form).permit(:product_id, :price, :quantity, :order_id)
    end

    # Method to authorize actions
    def authorize_action
      return authorize OrderLine.find(params[:id]) if params[:id]

      authorize OrderLine
    end

    # Method to create an order, if there is not an order id referenced in the session
    def set_order
      return @order = Order.find(session[:order_id]) if session[:order_id]

      @order = Order.create(user: current_user)
      session[:order_id] = @order.id
    end

    # Method to reset values of session storage
    def reset_session
      session[:checkout] = nil
      session[:product_id] = nil
      session[:id] = nil
      session[:order_id] = @order_line.order_id if @order_line
    end

    # Method to set values in session storage
    def set_values
      session[:product_id] = params[:product_id]
      session[:id] = params[:id]
    end
  end
end

app/controllers/customer/order_lines_controller.rb
# frozen_string_literal: true

module Customer
  # Class to manage interactions between customer users and order lines of a shopping cart
  class OrderLinesController < ApplicationController
    skip_before_action :load_pending_order
    before_action :set_order_line
    before_action :authorize_action
    after_action :reset_checkout

    # Method to delete an order line of the shopping cart
    # - DELETE /customer/order_lines/:id
    def destroy
      run Operations::Customer::OrderLines::Delete
      redirect_to shopping_cart_path, notice: 'Product was successfully deleted'
    #   Customer::OrderLineDeleter.call(@order_line)
    #   redirect_to shopping_cart_path, notice: 'Line was successfully deleted'
    # rescue StandardError => e
    #   flash[:alert] = e
    #   session[:order_id] = nil
    #   redirect_to products_path
    end

    private

    # Method to authorize actions
    def authorize_action
      authorize @order_line
    end

    # Method to set a specific order line
    def set_order_line
      @order_line = OrderLine.find(params[:id])
    end

    def reset_checkout
      session[:checkout] = nil
    end
  end
end

app/controllers/customer/orders_controller.rb
# frozen_string_literal: true

module Customer
  # Class to manage Orders Controller of the namespace from customer
  class OrdersController < ApplicationController
    before_action :authenticate_user!, only: %i[index show update]
    before_action :set_order, only: %i[show update destroy]
    before_action :authorize_action, only: %i[show update destroy]
    after_action :update_session, only: %i[update destroy]

    # Method to get index of completed orders of a customer user
    # - GET customer/orders
    def index
      authorize Order
      # @orders = Customer::OrderLister.call(current_user, 'completed')
      run Operations::Customer::Orders::Index, current_user:, status: 'completed' do |ctx|
        @orders = ctx[:orders]
      end
    end

    # Method to get show of an order of a customer user
    # - GET customer/orders/:id
    def show
      result = Operations::Customer::Orders::Show.call(
        params:, current_user:
      )
      @comment_order_form = result['contract.default']
      @information = result[:information]
      # @comment_order_form = Customer::OrderShower.call({ order_id: params[:id] }, current_user)
      # authorize @commentable
    end

    # Method to update an order to status completed of a customer user
    # - PATCH customer/orders/:id
    # def update
    #   @order = Customer::OrderBuyer.call(@order)
    #   if @order
    #     redirect_to products_path, notice: 'Thanks for buy'
    #   else
    #     render :new, status: :unprocessable_entity
    #   end
    # end

    # Method to delete an order
    # DELETE /customer/orders/:id
    def destroy
    #   Customer::OrderDeleter.call(@order)
    #   redirect_to products_path, notice: 'Shopping cart was successfully deleted'
    # rescue StandardError => e
    #   flash[:error] = e
    #   session[:order_id] = nil
    #   redirect_to products_path
      run Operations::Customer::Orders::Delete do
        return redirect_to products_path, notice: 'Shopping cart was successfully deleted'
      end
      flash[:error] = 'The purchase has been completed'
      session[:order_id] = nil
      redirect_to products_path
    end

    private

    # Method to set order
    def set_order
      @order = Order.find(params[:id])
    end

    # Method to update values of session storage
    def update_session
      session[:order_id] = nil
      session[:checkout] = nil
    end

    # Method to autorize actions
    def authorize_action
      authorize @order
    end
  end
end

app/controllers/customer/shopping_cart_controller.rb
# frozen_string_literal: true

module Customer
  # Class to manage interactions between customer users and shopping cart
  class ShoppingCartController < ApplicationController
    # Method to delete all the lines of a shopping cart
    # - GET /customer/empty_cart
    def empty_cart
      run Operations::Customer::ShoppingCart::Empty do
        return redirect_to shopping_cart_path, notice: 'Shopping cart has been emptied'
      end
      flash[:alert] = 'The purchase has been completed'
      session[:order_id] = nil
      redirect_to products_path
    #   Customer::ShoppingCartEmptier.call(params[:order_id])
    #   redirect_to shopping_cart_path, notice: 'Shopping cart has been emptied successfully'
    # rescue StandardError => e
    #   flash[:alert] = e
    #   session[:order_id] = nil
    #   redirect_to products_path
    end

    # Method to checkout if there is enough stock for all the products of a shopping cart
    # - GET /customer/checkout
    # def checkout
    #   session[:checkout] = Customer::CheckoutHandler.call(session[:order_id])
    #   redirect_to shopping_cart_path
    # rescue StandardError => e
    #   flash[:alert] = e
    #   session[:order_id] = nil
    #   redirect_to products_path
    # end
  end
end

app/controllers/customer/transactions_controller.rb
# frozen_string_literal: true

module Customer
  # Class to manage transactions of a customer
  class TransactionsController < ApplicationController
    before_action :authenticate_user!, only: %i[index]

    def index
      # @transactions = Customer::TransactionService.call(current_user)
      run Operations::Customer::Transactions::Index, current_user: do |ctx|
        @transactions = ctx[:transactions]
      end
      # authorize @transactions.first
    end
  end
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

# Module for Order Helpers
module OrdersHelper
end

app/views/customer/orders/index.html.erb
<h1>My Orders</h1>
<% if @orders.empty? %>
  <p>Empty Orders</p>
<% else %>
  <% @orders.each.with_index do |order, index| %>
    <h3>Order <%= index + 1 %></h3>
    <table class='table table-striped'>
      <thead>
        <th>#</th>
        <th style='text-align: center'>Product</th>
        <th style='text-align: center'>Quantity</th>
        <th style='text-align: center'>Price</th>
        <th style='text-align: center'>Subtotal</th>
      </thead>
      <tbody>
        <% order.order_lines.each.with_index do |order_line,i| %>
          <tr>
            <td style='vertical-align: middle'><%= i+1 %></td>
            <td style='text-align: center; vertical-align: middle'><%= order_line.product.name %></td>
            <td style='text-align: center; vertical-align: middle'><%= order_line.quantity %></td>
            <td style='vertical-align: middle'><%= format('$ %0.02f', order_line.price/100) %></td>
            <td style='vertical-align: middle'><%= format('$ %0.02f', order_line.total/100) %></td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="7">
            <div class='d-flex gap-4 align-items-center'>
              <%= link_to [:customer, order], class:'btn btn-primary' do %>
              <i class="bi bi-card-text"></i>
              <% end %>
              <h5 class='mb-0'>Total: <%= format('$ %0.02f', order.total/100) %></h5>
            </div>
          </td>
        </tr>
      </tfoot>
    </table>
  <% end %>
<% end %>

app/views/customer/orders/show.html.erb
<h3>Order bought on <%= @information.commentable.updated_at.to_fs(:db) %></h3>
<p class='my-3 mb-2 fs-5'><strong>Rate: </strong><%= @information.rate&.value || 'No rated' %></p>
<table class='table table-striped'>
  <thead>
    <th>#</th>
    <th style='text-align: center'>Product</th>
    <th style='text-align: center'>Quantity</th>
    <th style='text-align: center'>Price</th>
    <th style='text-align: center'>Subtotal</th>
  </thead>
  <tbody>
    <% @information.commentable.order_lines.each.with_index do |order_line,i| %>
      <tr>
        <td style='vertical-align: middle'><%= i+1 %></td>
        <td style='text-align: center; vertical-align: middle'><%= order_line.product.name %></td>
        <td style='text-align: center; vertical-align: middle'><%= order_line.quantity %></td>
        <td style='vertical-align: middle'><%= format('$ %0.02f', order_line.price/100) %></td>
        <td style='vertical-align: middle'><%= format('$ %0.02f', order_line.total/100) %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="7">
        <h5 class='mb-0'>Total: <%= format('$ %0.02f', @information.commentable.total/100) %></h5>
      </td>
    </tr>
  </tfoot>
</table>
<h4>Add a comments</h4>
<div data-turbo='false'>
  <%= form_for @comment_order_form, as: :comment, url: customer_comment_orders_path do |form| %>
    <div class="field mb-3">
      <% if flash[:error] %>
        <div class="alert alert-danger pb-1" role="alert">
          <ul>
            <%= decorate(ErrorForm.new('error')).list_errors(flash[:error]) %>
          </ul>
        </div>
      <% end %>
      <%= form.hidden_field :order_id, value: @information.commentable.id %>
      <%= form.text_area :description, class: 'form-control' %>
      <div class='mt-3'>
        <% unless @comment_order_form.errors.messages_for(:description).empty? %>
          <% @comment_order_form.errors.messages_for(:description).each do |message| %>
            <p class='text-danger fw-semibold'>* <%= message %></p>
          <% end %>
        <% end %>
      </div>
      <%= form.label :rate_value, 'Rate',class:'form-label' %>
      <em>(If you want you could rate or update your rate)</em>
      <%= form.text_field :rate_value, class: 'form-control' %>
      <div class='mt-3'>
        <% unless @comment_order_form.errors.messages_for(:rate_value).empty? %>
          <% @comment_order_form.errors.messages_for(:rate_value).each do |message| %>
            <p class='text-danger fw-semibold'>* <%= message %></p>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="d-grid mb-3">
      <%= form.submit 'Add Comment', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>
<div>
  <% if @information.commentable.comments.empty? %>
    <h4>No Comments</h4>
  <% else %>
    <h4>Comments</h4>
    <% @information.commentable.comments.each do |comment| %>
      <hr>
      <p><%= comment.description %></p>
      <p><%= time_ago_in_words(comment.created_at) %></p>
    <% end %>
  <% end %>
</div>