config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  resources :apidocs, only: [:index]
  get '/api' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')

  devise_for :users
  root 'products#index'

  resources :products, only: %i[index show]

  resources :order_lines, only: %i[new create edit update destroy]

  resources :orders, only: %i[show destroy]

  namespace :admin do
    resources :products, only: %i[destroy] do
      post "add_tag", on: :member
    end
    resources :change_logs, only: %i[index]
    resources :product_forms, only: %i[new create edit update]
    resources :comments, only: %i[destroy]
    patch 'comments/approve' => 'comments#approve'
    resources :transactions, only: %i[index]
  end

  namespace :customer do
    resources :orders, only: %i[index show update destroy]
    resources :likes, only: %i[create destroy]
    resources :order_lines, only: %i[destroy]
    resources :order_line_forms, only: %i[new create edit update]
    resources :comment_products, only: %i[create]
    resources :comment_orders, only: %i[create]
    get 'empty_cart' => 'shopping_cart#empty_cart'
    get 'checkout' => 'shopping_cart#checkout'
    resources :transactions, only: %i[index]
  end

  get 'shopping_cart', to: 'shopping_cart#index'
  get 'empty_cart' => 'shopping_cart#empty_cart'
  get 'checkout' => 'shopping_cart#checkout'

  resources :order_line_forms, only: %i[new create edit update]

  # Api routes
  namespace :api do
    namespace :v1 do
      post '/sign_in' => 'sessions#sign_in'
      resources :products, only: %i[index show]
      # namespace :customer do
        resources :likes, only: %i[create destroy]
        resources :order_lines, only: %i[create]
        resources :orders, only: %i[index]
        resources :comment_users, only: %i[create]
        get 'checkout' => 'orders#checkout'
        resources :transactions, only: %i[index]
      # end
      namespace :admin do
        resources :products, only: %i[index show create update destroy] do 
          patch 'discard', on: :member
          patch 'restore', on: :member
        end
        resources :comments, only: %i[destroy] do
          patch 'approve', on: :member
        end 
        resources :users, only: %i[create] do 
          patch 'discard', on: :member
          patch 'restore', on: :member
        end
        resources :transactions, only: %i[index]
      end
      post 'registration' => 'registration#create'
    end
  end

  get 'forgot_password' => 'password#forgot_password'
  post 'reset_password' => 'password#reset_password'

  post 'checkout_pay' => 'checkout_pay#create'
  resources :webhooks, only: %i[create]
  post 'webhooks/checkout_session_completed' => 'webhooks#checkout_session_completed'
  post 'webhooks/payment_failed' => 'webhooks#payment_failed'
end

app/controllers/customer/order_line_forms_controller.rb
# frozen_string_literal: true

module Customer
  # Class to manage interactions between logged in customer users and order lines of a shopping cart
  class OrderLineFormsController < ApplicationController
    skip_before_action :load_pending_order
    before_action :set_order, only: %i[create update]
    before_action :authorize_action
    after_action :reset_session, only: %i[create update]
    after_action :set_values, only: %i[new edit]

    # Method to get the form to add a new product (order line) to shopping cart
    # - GET /customer/order_line_forms/new
    def new
      run Operations::Customer::OrderLines::Create::Present do |ctx|
        @order_line_form = ctx['contract.default']
        @product = ctx[:product]
      end
    end

    # Method to add a new product (order line) to shopping cart
    # - POST /customer/order_line_forms
    def create
      ctx = run Operations::Customer::OrderLines::Create, params:, current_user:, order: @order do
        return redirect_to shopping_cart_path, notice: 'Product was successfully added'
      end
      @product = ctx[:product]
      @order_line_form = ctx['contract.default']
      render :new
    end

    # Method to get the form to update an order line of the shopping cart
    # - GET /customer/order_line_forms/:id/edit
    def edit
      # @order_line_form = Customer::OrderLines::EditFormGetter.call({ id: params[:id], product_id: params[:product_id] },
      #                                                              current_user)

      run Operations::Customer::OrderLines::Update::Present, params: do |ctx|
        @order_line_form = ctx['contract.default']
        @product = ctx[:product]
      end

      # rescue StandardError => e
      #   flash[:alert] = e
      #   session[:order_id] = nil
      # redirect_to products_path
    end

    # Method to update an order line of the shopping cart
    # - PATCH /customer/order_line_forms/:id
    def update
      # @order_line = Customer::OrderLines::OrderLineUpdater.call(order_line_form_params, @order)
      # redirect_to shopping_cart_path, notice: 'Quantity was successfully updated'
      ctx = run Operations::Customer::OrderLines::Update, params:, order: @order do
        return redirect_to shopping_cart_path, notice: 'Quantity was successfully updated'
      end
      @product = ctx[:product]
      @order_line_form = ctx['contract.default']
      render :edit
    # rescue StandardError => e
    #   flash[:error] = e
    #   redirect_to edit_customer_order_line_form_path(product_id: session[:product_id])
    end

    private

    # Method to set strong paramas for order line form
    def order_line_form_params
      params.require(:forms_order_line_form).permit(:product_id, :price, :quantity, :order_id)
    end

    # Method to authorize actions
    def authorize_action
      return authorize OrderLine.find(params[:id]) if params[:id]

      authorize OrderLine
    end

    # Method to create an order, if there is not an order id referenced in the session
    def set_order
      return @order = Order.find(session[:order_id]) if session[:order_id]

      @order = Order.create(user: current_user)
      session[:order_id] = @order.id
    end

    # Method to reset values of session storage
    def reset_session
      session[:checkout] = nil
      session[:product_id] = nil
      session[:id] = nil
      session[:order_id] = @order_line.order_id if @order_line
    end

    # Method to set values in session storage
    def set_values
      session[:product_id] = params[:product_id]
      session[:id] = params[:id]
    end
  end
end

app/controllers/order_line_forms_controller.rb
# frozen_string_literal: true

# Class to manage interactions between no logged in users and virtula order lines of a shopping cart
class OrderLineFormsController < ApplicationController
  before_action :set_virtual_order, only: %i[create edit update]
  after_action :update_session, only: %i[create update]
  after_action :set_values, only: %i[new edit]

  # Method to get the form to add a new product (order line) to the shopping cart
  # - GET /order_line_forms/new
  def new
    run Operations::Customer::OrderLines::Create::Present, params: do |ctx|
      @order_line_form = ctx['contract.default']
      @product = ctx[:product]
    end
    # @order_line_form = Customer::OrderLines::NewFormGetter.call(product_id: params[:product_id])
  end

  # Method to add a new product (order line) to the shopping cart
  # - POST /order_line_forms
  def create
  #   VirtualOrderLineCreator.new(order_line_form_params, @virtual_order).call
  #   redirect_to shopping_cart_path, notice: 'Product was successfully added'
  # rescue StandardError => e
  #   flash[:error] = e
  #   redirect_to new_order_line_form_path(product_id: session[:product_id])
    ctx = run Operations::VirtualOrderLines::Create, params:, virtual_order: @virtual_order do
      return redirect_to shopping_cart_path, notice: 'Product was successfully added'
    end
    # ctx = run Operations::Virtual::Create, params:, virtual_order: @virtual_order do
    #   return redirect_to shopping_cart_path, notice: 'Product was successfully added'
    # end
    @product = ctx[:product]
    @order_line_form = ctx['contract.default']
    render :new
  end

  # Method to get the form to update an order line of the shopping cart
  # - GET /order_line_forms/:id/edit
  def edit

    # @order_line_form = Customer::OrderLines::EditFormGetter.call(
    #   { product_id: params[:id],
    #     price: params[:price],
    #     quantity: params[:quantity] }
    # )
    run Operations::VirtualOrderLines::Update::Present, params: do |ctx|
      @order_line_form = ctx['contract.default']
      @product = ctx[:product]
    end
  end

  # Method to update an order line of the shopping cart
  # - PATCH /order_line_forms/:id
  def update
    ctx = run Operations::VirtualOrderLines::Update, params:, virtual_order: @virtual_order do
      return redirect_to shopping_cart_path, notice: 'Quantity was successfully updated'
    end
    @order_line_form = ctx['contract.default']
    @product = ctx[:product]
    render :edit
  #   VirtualOrderLineUpdater.call(order_line_form_params, @virtual_order)
  #   redirect_to shopping_cart_path, notice: 'Quantity was successfully updated'
  # rescue StandardError => e
  #   flash[:error] = e
  #   redirect_to edit_order_line_form_path(id: session[:product_id],
  #                                         price: session[:price], quantity: session[:quantity])
  end

  private

  # Method to set strong paramas for order line form
  def order_line_form_params
    params.require(:forms_order_line_form).permit(:product_id, :price, :quantity)
  end

  # Method to create a virtual order to save it in the session storage
  def set_virtual_order
    return @virtual_order = session[:virtual_order] if session[:virtual_order]

    @virtual_order = []
    session[:virtual_order] = @virtual_order
  end

  # Method to update values of session
  def update_session
    session[:checkout] = nil
    session[:virtual_order] = @virtual_order
    session[:product_id] = nil
  end

  def set_values
    session[:product_id] = params[:product_id] || params[:id]
    session[:price] = params[:price]
    session[:quantity] = params[:quantity]
  end
end

app/views/order_line_forms/edit.html.erb
<div class='d-flex flex-column align-items-center'>
  <h2 class='mb-4'>Edit Line</h2>
  <div class="card p-2" style="width: 20rem;">
    <div class="card-body">
      <h5 class="card-title">Product: <%= @product.name %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= format('$ %0.02f', @product.price/100) %></h6>
      <p class="card-text"><%= @product.description %></p>
      <div data-turbo=false>
        <%= form_for @order_line_form, as: :order_line, url: order_line_form_path(id: @product.id), method: :patch do |form| %>
          <%= form.hidden_field :price, value: @product.price %>
          <%= form.hidden_field :product_id, value: @product.id %>
          <div class="field mb-3">
            <%= form.label :quantity, class:'form-label' %>
            <%= form.text_field :quantity,class: 'form-control' %>
            <div class='mt-3'>
              <% unless @order_line_form.errors.messages_for(:quantity).empty? %>
                <% @order_line_form.errors.messages_for(:quantity).each do |message| %>
                  <p class='text-danger fw-semibold'>* <%= message %></p>
                <% end %>
              <% end %>
              <% if flash[:error] %>
                <div class="alert alert-danger py-2" role="alert">
                  <ul>
                    <%= decorate(ErrorForm.new('error')).list_errors(flash[:error]) %>
                  </ul>
                </div>
              <% end %>
            </div>
          </div>
          <div class="d-grid mb-3">
            <%= form.submit 'Edit Line', class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/order_line_forms/new.html.erb
<div class='d-flex flex-column align-items-center'>
  <h2 class='mb-4'>Add to Shopping Cart</h2>
  <div class="card p-2" style="width: 20rem;">
    <div class="card-body">
      <h5 class="card-title">Product: <%= @product.name %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= format('$ %0.02f', @product.price/100) %></h6>
      <p class="card-text"><%= @product.description %></p>
      <div data-turbo='false'>
        <%= form_for @order_line_form, as: :order_line, url: order_line_forms_path do |form| %>
          <%= form.hidden_field :price, value: @product.price %>
          <%= form.hidden_field :product_id, value: @product.id %>
          <div class="field mb-3">
            <%= form.label :quantity, class:'form-label' %>
            <%= form.text_field :quantity, value: 1, class: 'form-control' %>
            <div class='mt-3'>
              <% unless @order_line_form.errors.messages_for(:quantity).empty? %>
                <% @order_line_form.errors.messages_for(:quantity).each do |message| %>
                  <p class='text-danger fw-semibold'>* <%= message %></p>
                <% end %>
              <% end %>
              <% if flash[:error] %>
                <div class="alert alert-danger pb-1" role="alert">
                  <ul>
                    <%= decorate(ErrorForm.new('error')).list_errors(flash[:error]) %>
                  </ul>
                </div>
              <% end %>
            </div>
          </div>
          <div class="d-grid mb-3">
            <%= form.submit 'Add Product', class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>