config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  resources :apidocs, only: [:index]
  get '/api' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')

  devise_for :users
  root 'products#index'

  resources :products, only: %i[index show]

  resources :order_lines, only: %i[new create edit update destroy]

  resources :orders, only: %i[show destroy]

  namespace :admin do
    resources :products, only: %i[destroy] do
      post "add_tag", on: :member
    end
    resources :change_logs, only: %i[index]
    resources :product_forms, only: %i[new create edit update]
    resources :comments, only: %i[destroy]
    patch 'comments/approve' => 'comments#approve'
    resources :transactions, only: %i[index]
  end

  namespace :customer do
    resources :orders, only: %i[index show update destroy]
    resources :likes, only: %i[create destroy]
    resources :order_lines, only: %i[destroy]
    resources :order_line_forms, only: %i[new create edit update]
    resources :comment_products, only: %i[create]
    resources :comment_orders, only: %i[create]
    get 'empty_cart' => 'shopping_cart#empty_cart'
    get 'checkout' => 'shopping_cart#checkout'
    resources :transactions, only: %i[index]
  end

  get 'shopping_cart', to: 'shopping_cart#index'
  get 'empty_cart' => 'shopping_cart#empty_cart'
  get 'checkout' => 'shopping_cart#checkout'

  resources :order_line_forms, only: %i[new create edit update]

  # Api routes
  namespace :api do
    namespace :v1 do
      post '/sign_in' => 'sessions#sign_in'
      resources :products, only: %i[index show]
      # namespace :customer do
        resources :likes, only: %i[create destroy]
        resources :order_lines, only: %i[create]
        resources :orders, only: %i[index]
        resources :comment_users, only: %i[create]
        get 'checkout' => 'orders#checkout'
        resources :transactions, only: %i[index]
      # end
      namespace :admin do
        resources :products, only: %i[index show create update destroy] do 
          patch 'discard', on: :member
          patch 'restore', on: :member
        end
        resources :comments, only: %i[destroy] do
          patch 'approve', on: :member
        end 
        resources :users, only: %i[create] do 
          patch 'discard', on: :member
          patch 'restore', on: :member
        end
        resources :transactions, only: %i[index]
      end
      post 'registration' => 'registration#create'
    end
  end

  get 'forgot_password' => 'password#forgot_password'
  post 'reset_password' => 'password#reset_password'

  post 'checkout_pay' => 'checkout_pay#create'
  resources :webhooks, only: %i[create]
  post 'webhooks/checkout_session_completed' => 'webhooks#checkout_session_completed'
  post 'webhooks/payment_failed' => 'webhooks#payment_failed'
end

app/controllers/api/v1/shopping_cart_controller.rb
# frozen_string_literal: true

module Api
  module V1
    # module Customer
    # Class to manage shopping cart since api
    class ShoppingCartController < ApiController
      before_action :authorize_request
      before_action :authorize_action

      # Method to checkout if there is enough stock for all the products of a shopping cart
      # - GET /api/v1/customer/checkout
      # def checkout
      #   @order = Customer::CheckoutHandlerApi.call(params[:order_id])
      #   # puts 'Herrrrrrr'
      #   # authorize Order
      #   render json: json_api_format(OrderRepresenter.new(@order), 'order'), status: :ok
      # end
    end
    # end

    # private

    # def authorize_action
    #   authorize Order
    # end
  end
end

app/controllers/customer/shopping_cart_controller.rb
# frozen_string_literal: true

module Customer
  # Class to manage interactions between customer users and shopping cart
  class ShoppingCartController < ApplicationController
    # Method to delete all the lines of a shopping cart
    # - GET /customer/empty_cart
    def empty_cart
      run Operations::Customer::ShoppingCart::Empty do
        return redirect_to shopping_cart_path, notice: 'Shopping cart has been emptied'
      end
      flash[:alert] = 'The purchase has been completed'
      session[:order_id] = nil
      redirect_to products_path
    #   Customer::ShoppingCartEmptier.call(params[:order_id])
    #   redirect_to shopping_cart_path, notice: 'Shopping cart has been emptied successfully'
    # rescue StandardError => e
    #   flash[:alert] = e
    #   session[:order_id] = nil
    #   redirect_to products_path
    end

    # Method to checkout if there is enough stock for all the products of a shopping cart
    # - GET /customer/checkout
    # def checkout
    #   session[:checkout] = Customer::CheckoutHandler.call(session[:order_id])
    #   redirect_to shopping_cart_path
    # rescue StandardError => e
    #   flash[:alert] = e
    #   session[:order_id] = nil
    #   redirect_to products_path
    # end
  end
end

app/controllers/shopping_cart_controller.rb
# frozen_string_literal: true

# Class to manage interactions between no logged in users and shopping cart (except index this metho is for all users)
class ShoppingCartController < ApplicationController
  # Method to show shopping cart
  # - GET /shopping_cart
  def index
    run Operations::ShoppingCart::Index,
        params:, current_user:,
        order_id: session[:order_id], virtual_order: session[:virtual_order] do |ctx|
      @order = ctx[:order]
      @virtual_order = ctx[:virtual_order]
      return
    end
    flash[:alert] = 'The purchase has been completed'
    session[:order_id] = nil
    redirect_to products_path

  #   @order, @virtual_order = OrdersSetter.call(current_user, session[:order_id], session[:virtual_order])
  # rescue StandardError => e
  #   flash[:alert] = e
  #   session[:order_id] = nil
  #   redirect_to products_path
  end

  # Method to delete all the lines of a shopping cart
  # - GET /empty_cart
  def empty_cart
    # session[:virtual_order] = ShoppingCartEmptier.call
    session[:virtual_order] = nil
    redirect_to shopping_cart_path, notice: 'Shopping cart has been emptied successfully'
  end

  # Method to checkout if there is enough stock for all the products of a shopping cart
  # - GET /checkout
  # def checkout
  #   session[:checkout] = CheckoutHandler.call(session[:virtual_order])
  #   redirect_to shopping_cart_path
  # end
end

app/helpers/shopping_cart_helper.rb
# frozen_string_literal: true

# Module for Shopping Cart Helpers
module ShoppingCartHelper
  def show_empty_messsage?(virtual_order, current_user, order)
    (virtual_order.nil? && current_user.nil?) || (current_user && order.order_lines.empty?)
  end
end

app/views/shopping_cart/_details_shop_cart.html.erb
<tbody>
  <% virtual_order.each.with_index do |order_line,i| %>
    <tr>
      <td style='vertical-align: middle'><%= i+1 %></td>
      <td style='text-align: center; vertical-align: middle'><%= order_line['name'] %></td>
      <td style='text-align: center; vertical-align: middle'><%= order_line['quantity'] %></td>
      <td style='vertical-align: middle'><%= format('$ %0.02f', order_line['price']/100) %></td>
      <td style='vertical-align: middle'><%= format('$ %0.02f', order_line['quantity'].to_i * order_line['price'].to_f/100) %></td>
      <td style='text-align: center'>
        <%= link_to edit_order_line_form_path(id: order_line['id'], price: order_line['price'], quantity: order_line['quantity']), class:'btn btn-primary' do %>
          <i class="bi bi-pencil"></i>
        <% end %>
      </td>
      <td style='text-align: center'>
        <%= link_to order_line_path(id: order_line['id']), data: {turbo_method: :delete}, class:'btn btn-danger' do %>
          <i class="bi bi-trash"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
</tbody>
<tfoot>
  <tr>
    <td colspan="7">
      <h5 class='mb-0'>
        Total: <%= decorate(Order.new).total_virtual_order(@virtual_order) %>
        </h5>
      </td>
  </tr>
</tfoot>

app/views/shopping_cart/index.html.erb
<div class='d-flex justify-content-center mb-3'>
  <h1>Current Cart</h1>
</div>
<div>
  <% if show_empty_messsage?(session[:virtual_order], current_user, @order) %>
    <div class="alert alert-info d-flex justify-content-center fw-semibold fs-5 py-4" role="alert">
      Your cart its empty
    </div>
  <% else %>
    <table class='table table-striped'>
      <thead>
        <th>#</th>
        <th style='text-align: center'>Product</th>
        <th style='text-align: center'>Quantity</th>
        <th style='text-align: center'>Price</th>
        <th style='text-align: center'>Subtotal</th>
        <th></th>
        <th></th>
      </thead>
      <% if current_user %>
        <%= render 'customer/shopping_cart/details_shop_cart', order: @order %>
      <% else %>
        <%= render 'details_shop_cart', virtual_order: @virtual_order %>
      <% end %>
    </table>
    <div class='d-flex gap-2 mt-3'>
      <% if current_user %>
        <%= link_to 'Empty cart', customer_empty_cart_path(order_id: session[:order_id]), class:'btn btn-primary' %>
        <%# link_to 'Checkout', customer_checkout_path, class:'btn btn-primary' %>
        <div data-turbo='false'>
          <%= button_to 'Checkout', checkout_pay_path, class:'btn btn-primary' %>
        </div>
      <% else %>
        <%= link_to 'Empty cart', empty_cart_path(order_id: session[:order_id]), class:'btn btn-primary' %>
        <%# link_to 'Checkout', checkout_path, class:'btn btn-primary' %>
        <div data-turbo='false'>
          <%= button_to 'Checkout', checkout_pay_path, class:'btn btn-primary' %>
        </div>
      <% end %>
    </div>
    <% unless session[:checkout].nil? %>
      <% if session[:checkout].empty? %>
        <div data-turbo='false' class='mt-3'>
          <%# button_to 'Buy', customer_order_path(id: session[:order_id] || 0), method: :patch, class:'btn btn-primary' %>
          <%# button_to 'Buy', checkout_pay_path, class:'btn btn-primary' %>
        </div>
      <% else %>
        <p>
          <ul>
            <% session[:checkout].each do |line| %>
              <% if current_user %>
                <li class='text-danger fw-semibold'>
                  <%# "There is only a stock of #{line['stock']} for #{line['name']}" %>
                </li>
              <% else %>
                <li class='text-danger fw-semibold'>
                  <%# "There is only a stock of #{line['stock']} for #{line['line']['name']}" %>
                </li>
              <% end %>
            <% end %>
          </ul>
        </p>
      <% end %>
    <% end %>
  <% end %>
  <div class='mt-3'>
    <% if current_user %>
      <%= button_to 'Delete cart', [:customer, @order], method: :delete, class:'btn btn-danger' %>
    <% end %>
  </div>
</div>