config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  resources :apidocs, only: [:index]
  get '/api' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')

  devise_for :users
  root 'products#index'

  resources :products, only: %i[index show]

  resources :order_lines, only: %i[new create edit update destroy]

  resources :orders, only: %i[show destroy]

  namespace :admin do
    resources :products, only: %i[destroy] do
      post "add_tag", on: :member
    end
    resources :change_logs, only: %i[index]
    resources :product_forms, only: %i[new create edit update]
    resources :comments, only: %i[destroy]
    patch 'comments/approve' => 'comments#approve'
    resources :transactions, only: %i[index]
  end

  namespace :customer do
    resources :orders, only: %i[index show update destroy]
    resources :likes, only: %i[create destroy]
    resources :order_lines, only: %i[destroy]
    resources :order_line_forms, only: %i[new create edit update]
    resources :comment_products, only: %i[create]
    resources :comment_orders, only: %i[create]
    get 'empty_cart' => 'shopping_cart#empty_cart'
    get 'checkout' => 'shopping_cart#checkout'
    resources :transactions, only: %i[index]
  end

  get 'shopping_cart', to: 'shopping_cart#index'
  get 'empty_cart' => 'shopping_cart#empty_cart'
  get 'checkout' => 'shopping_cart#checkout'

  resources :order_line_forms, only: %i[new create edit update]

  # Api routes
  namespace :api do
    namespace :v1 do
      post '/sign_in' => 'sessions#sign_in'
      resources :products, only: %i[index show]
      # namespace :customer do
        resources :likes, only: %i[create destroy]
        resources :order_lines, only: %i[create]
        resources :orders, only: %i[index]
        resources :comment_users, only: %i[create]
        get 'checkout' => 'orders#checkout'
        resources :transactions, only: %i[index]
      # end
      namespace :admin do
        resources :products, only: %i[index show create update destroy] do 
          patch 'discard', on: :member
          patch 'restore', on: :member
        end
        resources :comments, only: %i[destroy] do
          patch 'approve', on: :member
        end 
        resources :users, only: %i[create] do 
          patch 'discard', on: :member
          patch 'restore', on: :member
        end
        resources :transactions, only: %i[index]
      end
      post 'registration' => 'registration#create'
    end
  end

  get 'forgot_password' => 'password#forgot_password'
  post 'reset_password' => 'password#reset_password'

  post 'checkout_pay' => 'checkout_pay#create'
  resources :webhooks, only: %i[create]
  post 'webhooks/checkout_session_completed' => 'webhooks#checkout_session_completed'
  post 'webhooks/payment_failed' => 'webhooks#payment_failed'
end

app/models/product.rb
# frozen_string_literal: true

# Class to manage Product Model
class Product < ApplicationRecord
  include Discard::Model

  # after_create :create_stripe_product

  # Associations
  has_many :order_lines, dependent: :destroy
  has_many :orders, through: :order_lines
  has_many :likes, dependent: :destroy
  has_and_belongs_to_many :tags
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :rates, as: :rateable, dependent: :destroy
  has_one_attached :image

  # Scopes
  default_scope { order(:name) }
  scope :order_by_price, -> { order(:price) }
  scope :get_most_purchased_product, lambda {
                                       joins(order_lines: :order).where('orders.status': 1).group(:id)
                                                                 .order('SUM(order_lines.quantity) DESC').limit(1)
                                     }

  def liked_by_current_user(current_user)
    likes.select { |like| like.user_id == current_user.id }.first
  end

  def pending_comments_of_user(current_user)
    comments.includes(:user).pending.where(user_id: current_user.id)
  end

  def aproved_comments_of_produc
    comments.includes(:user).approved
  end

  def comments_include_user
    comments.includes(:user)
  end

  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [220, 220]
  end

  # def create_stripe_product
  #   product = Stripe::Product.create(name:)
  #   price = Stripe::Price.create(product:, unit_amount: 2000, currency: 'usd')
  #   update(stripe_product_id: product.id)
  # end
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

# Class of the namespace Admin
module Admin
  # Class to manage interactions between admin users and products
  class ProductsController < ApplicationController
    before_action :set_product
    before_action :authenticate_user!
    before_action :authorize_action

    # Method to delete a product
    # - DELETE /admin/products/:id
    def destroy
      run Operations::Admin::Products::Delete
      redirect_to products_path, notice: 'Product was successfully deleted'
    end

    def add_tag
      # Admins::TagAdder.call(params[:tag_id], @product)
      run Operations::Admin::Products::AddTag
      redirect_to @product, notice: 'Tag was successfully added'
    end

    private

    # Method to set a specific product
    def set_product
      @product = Product.find(params[:id])
    end

    # Method to authorize actions
    def authorize_action
      authorize Product
    end
  end
end

app/controllers/api/v1/admin/products_controller.rb
# frozen_string_literal: true

module Api
  module V1
    module Admin
      # Class to manage interactions between no logged in users and products
      class ProductsController < ApiController
        before_action :authorize_request
        before_action :authorize_action
        before_action :set_product, only: %i[update discard]
        before_action :set_product_available, only: %i[destroy restore]

        # Method to get index of products
        # GET /api/v1/admin/products
        def index
          @pagy, @products = ProductService.call(params, @current_user, 'api')
          render json: json_api_format(ProductRepresenter.for_collection.new(@products), 'products', @pagy), status: :ok
        end

        # Method to get show product
        # GET /api/v1/products/:id
        def show
          run Operations::Api::V1::Admin::Products::Show,
              params:, user: @current_user do |ctx|
            @product = ctx[:model]
          end
          # ctx = run Operations::Api::V1::Admin::Products::Show,
          #           params:, user: @current_user
          # @product = ProductGetter.call(params[:id], @current_user)
          render json: json_api_format(ProductRepresenter.new(@product), 'product'), status: :ok
        end

        # Method to create a new product
        # - POST /api/v1/admin/products
        def create
          # @product = Admins::ProductCreator.call(new_product_form_params, @current_user, @token)
          run Operations::Api::V1::Admin::Products::Create,
              params:, user: @current_user, product_params: new_product_form_params do |ctx|
            @product = ctx[:product]
          end
          render json: json_api_format(ProductRepresenter.new(@product), 'product'), status: :ok
        end

        # Method to update a product
        # - PATCH /api/v1/admin/products/:id
        def update
          # @product = Admins::ProductUpdater.call(edit_product_form_params, params[:id], @current_user, @token)
          run Operations::Api::V1::Admin::Products::Update,
              params:, user: @current_user, product_params: edit_product_form_params do |ctx|
            @product = ctx[:model]
          end
          render json: json_api_format(ProductRepresenter.new(@product), 'product'), status: :ok
        end

        # Method to delete a product
        # - DELETE /api/v1/admin/products/:id
        def destroy
          run Operations::Admin::Products::Delete
          # @product = Admins::ProductDeleter.call(@product, @current_user)
          render json: @product, status: :no_content
        end

        # Method to soft delete a product
        # - PATCH /api/v1/admin/products/soft_delete/:id
        def discard
          run Operations::Api::V1::Admin::Products::Discard,
              params:, user: @current_user do |ctx|
            @product = ctx[:model]
          end
          # @product = Admins::ProductSoftDeleter.call(@product, @current_user)
          render json: json_api_format(ProductRepresenter.new(@product), 'product'), status: :ok
        end

        # Method to soft delete a product
        # - PATCH /api/v1/admin/products/soft_delete/:id
        def restore
          # @product = Admins::ProductRestorer.call(@product, @current_user)
          run Operations::Api::V1::Admin::Products::Restore,
              params:, user: @current_user do |ctx|
            @product = ctx[:model]
          end
          render json: json_api_format(ProductRepresenter.new(@product), 'product'), status: :ok
        end

        private

        # Method to set strong params for product form
        def new_product_form_params
          params.require(:forms_new_product_form).permit(policy(Product).permitted_attributes)
        end

        def edit_product_form_params
          params.require(:forms_edit_product_form).permit(policy(Product).permitted_attributes)
        end

        # Method to set a specific product
        def set_product
          @product = ProductGetter.call(params[:id])
        end

        # Method to set a specific product
        def set_product_available
          @product = Product.find(params[:id])
        end

        # Method to authorize actions
        def authorize_action
          authorize Product
        end
      end
    end
  end
end

app/controllers/api/v1/products_controller.rb
# frozen_string_literal: true

module Api
  module V1
    # Class to manage interactions between no logged in users and products
    class ProductsController < ApiController
      # before_action :doorkeeper_authorize!, only: %i[show]
      # before_action :doorkeeper_authorize!, only: %i[show]
      before_action :authorize_request, only: %i[show]
      # Method to get index of products
      # GET /api/v1/products
      def index
        @pagy, @products = ProductService.call(params, @current_user, 'api')
        render json: json_api_format(ProductRepresenter.for_collection.new(@products), 'products', @pagy), status: :ok
      end

      # Method to get show product
      # GET /api/v1/products/:id
      def show
        # @product = ProductGetter.call(params[:id], @current_user)
        @product = ProductGetter.call(params[:id])
        render json: json_api_format(ProductRepresenter.new(@product), 'product'), status: :ok
      end
    end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

# Class to manage interactions between no logged in users and products
class ProductsController < ApplicationController
  before_action :save_input_states, only: %i[index]
  # before_action :set_product, only: %i[show]

  # Method to get index of products
  # GET /products
  def index
    run Operations::Index, params:, current_user:, api: nil do |ctx|
      @products = ctx[:products]
    end
  end

  # Method to get show product
  # GET /products/:id
  def show
    result = Operations::Customer::Products::Show.call(
      params: { id: params[:id], current_user: }
    )
    @comment_product_form = result['contract.default']
    @information = result[:information]
  end

  private

  # Method to mantain options of search, filter and sort sections
  def save_input_states
    @search = params[:search].strip unless params[:search].nil?
    @selected_tags = params[:tags]
    @selected_sort = params[:sort]
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

# Module for Products Helpers
module ProductsHelper
end

app/views/products/index.html.erb
<div class="d-flex justify-content-center mb-4">
  <div class="col-sm-12 col-md-12 col-lg-12 ps-3">
    <%= form_with url: products_path, method: :get, class:"d-flex flex-column gap-3", role:"search" do |form| %>
      <div class='col-sm-8 col-md-8 col-lg-8 d-flex mx-auto'>
        <%= form.text_field :search, value: @search, placeholder: 'Name of product', require: true, class:"form-control me-2", type:"search", 'aria-label':"Search" %>
        <%= form.submit 'Apply Search', class: "btn btn-outline-primary" %>
      </div>
      <div class='d-flex gap-1 checkbox-group' style='font-size: 1.1rem'>
        <strong><%= form.label 'Filter by Tags:' %></strong>
        <%= form.collection_check_boxes :tags, Tag.all, :name, :name, checked: @selected_tags %>
      </div>
      <div class='d-flex gap-2 radio-button-group' style='font-size: 1.1rem'>
        <strong><%= form.label 'Sort by:' %></strong>
        <%= form.collection_radio_buttons :sort, Poro::Sort.sort_options, :query_param, :name, checked: @selected_sort %>
      </div>
    <% end %>
  </div>
</div>
<div class='container-md d-flex mb-3 gap-2'>
  <% if policy(Product).new? %>
    <%= link_to 'New Product', new_admin_product_form_path, class:'btn btn-primary' %>
  <% end %>
  <% if policy(ChangeLog).index? %>
    <%= link_to admin_change_logs_path, class:'btn btn-secondary' do %>
      <i class="bi bi-file-earmark-text"></i>
    <% end %>
  <% end %>
  <% if current_user&.admin? %>
    <%= link_to 'Log Transactions', admin_transactions_path, class:'btn btn-secondary' %>
  <% end %>
  <% if current_user.nil? || current_user&.customer? %>
    <% if session[:virtual_order] || session[:order_id] %>
      <%= link_to shopping_cart_path, class:'btn btn-primary' do %>
        <i class="bi bi-cart3"></i>
      <% end %>
    <% end %>
  <% end %>
  <% if current_user&.customer? %>
    <%= link_to 'My orders', customer_orders_path, class:'btn btn-primary' %>
    <%= link_to 'My Transactions', customer_transactions_path, class:'btn btn-secondary' %>
  <% end %>
</div>
<div class='container-md d-flex flex-column gap-4'>
  <% @products.each do |product| %>
    <div class="card px-3 py-2">
      <div class="card-body">
        <h6 class="card-subtitle mb-2 text-muted"><%= product.sku %></h6>
        <h5 class="card-title"><%= product.name %></h5>
        <p class="card-text"><%= product.description %></p>
        <h6 class="card-subtitle mb-3 text-muted d-flex gap-2"> 
          Tags: 
          <% if product.tags.empty? %>
            No tags assigned
          <% else %>
            <% product.tags.each do |tag| %>
              <div>
                <%= tag.name %>
              </div>
            <% end %>
          <% end %>
        </h6>
        <h6 class="card-subtitle mb-2 text-muted"><%= format('$ %0.02f', product.price/100) %></h6>
        <h6 class="card-subtitle mb-2 text-muted">Stock: <%= product.stock %></h6>
        <h6 class="card-subtitle mb-2 text-muted">Rate: 
          <% if product.rates.empty? %>
            No rated
          <% else %>
            <%= decorate(product).average_rate(product.rates) %>
          <% end %>
        </h6>
        <div class='d-flex justify-content-center mb-2'>
          <% if product.image.attached? %>
            <%= image_tag product.image.variant(:thumb).processed %>
          <% end %>
        </div>
        <% if current_user&.admin? %>
        <% end %>
        <%= link_to product, class:'btn btn-primary' do %>
          <i class="bi bi-eye"></i>
        <% end %>
        <div class='mt-3 d-flex justify-content-between align-items-center'>
          <div class='d-flex gap-0 align-items-center'>
            <% if policy(Like).create? %>
              <% if like = product.liked_by_current_user(current_user) %>
                <%= link_to [:customer, like], data: {turbo_method: :delete}, class:'btn fs-4' do %>
                  <i class="bi bi-star-fill text-info"></i>
                <% end %>
              <% else %>
                <%= link_to customer_likes_path(product_id: product.id), data: {turbo_method: :post}, class:'btn btn-ligth fs-4' do %>
                  <i class="bi bi-star"></i>
                <% end %>
              <% end %>
            <% end %>
            <p class='mb-0 mt-1'>
              <%= "#{product.likes_count} #{'like'.pluralize(product.likes_count)}" %>
            </p>
          </div>
          <div>
            <% if policy(product).edit? || current_user&.support? %>
              <%= link_to edit_admin_product_form_path(product), class:'btn btn-primary' do %>
                <i class="bi bi-pencil"></i>
              <% end %>
            <% end %>
            <% if policy(product).destroy? %>
              <%= link_to admin_product_path(product), data: { turbo_method: :delete }, class:'btn btn-danger' do %>
                <i class="bi bi-trash"></i>
              <% end %>
            <% end %>
            <% if policy(OrderLine).new? %>
              <% if current_user %>
                <%= link_to 'Add to cart', new_customer_order_line_form_path(product_id: product.id), class:'btn btn-primary' %>
              <% else %>
                <%= link_to 'Add to cart', new_order_line_form_path(product_id: product.id), class:'btn btn-primary' %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/products/show.html.erb
<p>
  <%= @information.commentable.sku %>
</p>
<h1><%= @information.commentable.name %></h1>
<p>
  <%= @information.commentable.description %>
</p>
<p>
  <div class='d-flex gap-2'>
    Tags: 
    <% if @information.commentable.tags.empty? %>
      No tags assigned
    <% else %>
      <% @information.commentable.tags.each do |tag| %>
        <div><%= tag.name %></div>
      <% end %>
    <% end %>
  </div>
</p>
<p>
  <%= format('$ %0.02f', @information.commentable.price/100) %>
</p>
<p>
  Stock: <%= @information.commentable.stock %>
</p>
<% if @current_user&.customer? %>  
  <p>
    Rate: 
    <% if @information.commentable.rates.empty? %>
      No rated
    <% else %>
      <%= decorate(@information.commentable).average_rate(@information.commentable.rates) %>
    <% end %>
  </p>
  <p>
    Your rate: <%= @information.rate&.value || 'No rated' %>
  </p>
<% end %>
<% if current_user&.admin? || current_user&.support? %>
  <div class='mb-3'>
    <h4>Add tags</h4>
    <div>
      <%= form_with url: add_tag_admin_product_path(@information.commentable) do |f|%>
        <%= f.collection_select :tag_id, (Tag.all - @information.commentable.tags), :id, :name, include_blank: "-- Select Tag" %>
        <%= f.submit "Add Tag", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
<% end %>
<% if @current_user&.customer? %> 
<h4>Add a comments</h4>
<div data-turbo='false'>
  <%= form_for @comment_product_form, as: :comment, url: customer_comment_products_path do |form| %>
    <div class="field mb-3">
      <% if flash[:error] %>
        <div class="alert alert-danger pb-1" role="alert">
          <ul>
            <%# decorate(ErrorForm.new('error')).list_errors(flash[:error]) %>
            <%= flash[:error] %>
          </ul>
        </div>
      <% end %>
      <%= form.hidden_field :product_id, value: @information.commentable.id %>
      <%= form.text_area :description, class: 'form-control' %>
      <div class='mt-3'>
        <% unless @comment_product_form.errors.messages_for(:description).empty? %>
          <% @comment_product_form.errors.messages_for(:description).each do |message| %>
            <p class='text-danger fw-semibold'>* <%= message %></p>
          <% end %>
        <% end %>
      </div> 
        <%= form.label :rate_value, 'Rate', class:'form-label' %>
        <em>(If you want you could rate or update your rate)</em>
        <%= form.text_field :rate_value, class: 'form-control' %>
        <div class='mt-3'>
          <% unless @comment_product_form.errors.messages_for(:rate_value).empty? %>
            <% @comment_product_form.errors.messages_for(:rate_value).each do |message| %>
              <p class='text-danger fw-semibold'>* <%= message %></p>
            <% end %>
          <% end %>
        </div>
    </div>
    <div class="d-grid mb-3">
      <%= form.submit 'Add Comment', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>
<% end %>
<% if current_user && ( current_user.admin? || current_user.support? ) %>
  <%= render 'admin/comments/comments', commentable: @information.commentable %>
<% elsif current_user && current_user.customer? %>
  <%= render 'customer/comments/comments', commentable: @information.commentable %>
<% else %>
  <%= render 'comments/comments', commentable: @information.commentable %>
<% end %>